# Generated by Django 2.1 on 2018-08-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageDatabase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unknown', max_length=100)),
                ('face_encoding', models.CharField(default='', max_length=32556)),
                ('face', models.ImageField(default='', upload_to='C:\\Users\\nxf45231\\Desktop\\Stuff\\SmartDoor\\static\\detection')),
            ],
        ),
    ]
