# Generated by Django 2.1 on 2018-08-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recognition', '0005_auto_20180828_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogsDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=100)),
                ('face', models.ImageField(default='', upload_to='C:\\Users\\nxf45231\\Desktop\\Stuff\\SmartDoor\\media')),
                ('timestamp', models.DateField(auto_now=True)),
                ('known', models.BooleanField(default=False)),
            ],
        ),
    ]
