# Generated by Django 2.1 on 2018-08-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recognition', '0006_logsdatabase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsdatabase',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
