# Generated by Django 2.1 on 2018-08-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recognition', '0007_auto_20180829_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedatabase',
            name='face',
            field=models.ImageField(default='', upload_to='snaps'),
        ),
        migrations.AlterField(
            model_name='logsdatabase',
            name='face',
            field=models.ImageField(default='', upload_to='timestamps'),
        ),
    ]
