# Generated by Django 2.1 on 2018-10-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recognition', '0008_auto_20180829_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedatabase',
            name='voice_sample1',
            field=models.FileField(default='', upload_to='samples/<name>'),
        ),
        migrations.AddField(
            model_name='imagedatabase',
            name='voice_sample2',
            field=models.FileField(default='', upload_to='samples/<name>'),
        ),
        migrations.AddField(
            model_name='imagedatabase',
            name='voice_sample3',
            field=models.FileField(default='', upload_to='samples/<name>'),
        ),
    ]
