# Generated by Django 2.1 on 2018-10-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recognition', '0009_auto_20181004_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedatabase',
            name='password',
            field=models.CharField(default='password', max_length=100),
        ),
    ]
